# docker-compose.yml

services:
  shondo-site:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    environment:
      NODE_ENV: production
    volumes:
      - ./public/uploads:/opt/app/public/uploads

  db:
    build: docker/db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: testing
    volumes:
      - ./docker/db/sql/:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/my.cnf
    ports:
      - 127.0.0.1:3306:3306

  webserver:
    build:
      context: ./
      dockerfile: ./docker/webserver/Dockerfile
    container_name: webserver
    volumes:
      - ./docker/webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/webserver/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/webserver/prod.conf:/etc/nginx/conf.d/site.conf
      - ./docker/webserver/shondo.co.uk.pem:/etc/ssl/shondo.co.uk.pem
      - ./docker/webserver/shondo.co.uk.key:/etc/ssl/shondo.co.uk.key
    ports:
      - "443:443"

  redis:
    image: redis:latest
    container_name: redis
    command: [ "redis-server" ]

volumes:
  dbdata:
  uploads: